"""empty message

Revision ID: 472b3145c0ef
Revises: 72025fb87d0f
Create Date: 2020-04-06 21:33:00.126348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '472b3145c0ef'
down_revision = '72025fb87d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'artist_id')
    )
    op.drop_table('Shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Shows',
    sa.Column('venue', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist'], ['Artist.id'], name='Shows_artist_fkey'),
    sa.ForeignKeyConstraint(['venue'], ['Venue.id'], name='Shows_venue_fkey'),
    sa.PrimaryKeyConstraint('venue', 'artist', name='Shows_pkey')
    )
    op.drop_table('Show')
    # ### end Alembic commands ###
